### ISSUE TITLE
retrain on saved pickle model?

### ISSUE THREAD

**Issue by RaiAmanRai** [davidberenstein1957/classy-classification#26]
Hi, is it possible to use the saved model and train it again using `ClassyClassifier`

It could look like this 

```
f = open("./classifier.pkl", "rb")
model = pickle.load(f)
```
use this model and then pass it to ClassyClassifier
```
classifier = ClassyClassifier(data=data, model)
```

**Comment by davidberenstein1957** [comment]
Hi, you could try [setting training](https://github.com/Pandora-Intelligence/classy-classification#standalone-usage-without-spacy) data via `set_training_data()`. or copy the previous data, then combine it and retrain based on that.
