### ISSUE TITLE
Misaligned pairings of labels and scores?

### ISSUE THREAD

**Issue by reneschneider** [davidberenstein1957/classy-classification#28]
Hi, thanks for your helpful package!

Trying your example code [https://github.com/Pandora-Intelligence/classy-classification#spacy-embeddings](https://github.com/Pandora-Intelligence/classy-classification#spacy-embeddings), I noticed two things: First, the output format seems to be different; instead of the list of dictionaries in your example code I get a single dictionary (not a big deal).
 
Second, and perhaps more importantly, it seems that the labels do not match the scores in a reasonable way. For example, `print(nlp("I am looking for fridge, stove and oven appliances.")._.cats)` returns `{'furniture': 0.7210517551092989, 'kitchen': 0.27894824489070125}`. While the scores seem somewhat reasonable, they should rather favor the 'kitchen' class in this example, shouldn't they? I could reproduce this with other examples and data, and on a different machine with a fresh Python (3.9.15), spacy (3.3.1) and classy_classification (0.6.1) installation.
 
Thank you very much for taking at look at this in advance!

**Comment by rasmusab** [comment]
Could it be that the order of the training examples given in the training data `dict` matters? If you put them in alphabetical order in the training data (`furniture` before `kitchen`, etc.) does this improve the results?

**Comment by joel-odlund** [comment]
The issue seems to appear when the labels in the training data is not in alphabetical order.  
If you order them alphabetically,  the outputs will be as expected.

I spent hours trying to figure out why the predictions were wrong.

**Comment by davidberenstein1957** [comment]
@rasmusab could you share your code please? Then I can have a bit more in-depth look.

**Comment by davidberenstein1957** [comment]
@joel-odlund thanks for looking into this.

**Comment by davidberenstein1957** [comment]
@reneschneider thank you for raising this. I just updated the docs

**Comment by davidberenstein1957** [comment]
@Masboes @rdeheer2 this is a huge issue, which you could start investigating and tackling.

**Comment by Masboes** [comment]
Thanks David, will add it to this sprint.

**Comment by davidberenstein1957** [comment]
This was fixed in version '0.6.3.' @reneschneider . Thanks for bringing this up.
