### ISSUE TITLE
add saving and loading support for `standalone` reproducability

### ISSUE THREAD

**Issue by davidberenstein1957** [davidberenstein1957/classy-classification#30]

**Comment by davidberenstein1957** [comment]
https://github.com/Pandora-Intelligence/classy-classification/issues/26

**Comment by davidberenstein1957** [comment]
@rdeheer2 @Masboes this is a typical task of something that every package has, but which I have never been able to find the time for.

**Comment by Masboes** [comment]
Thanks David, also adding this one to our backlog.
