### ISSUE TITLE
Running the first example we get a different score 

### ISSUE THREAD

**Issue by benhealthee** [davidberenstein1957/classy-classification#36]
{'furniture': 0.5352066861088035, 'kitchen': 0.4647933138911965}

**Comment by benhealthee** [comment]
Here is the code:
import spacy
import classy_classification
# or import standalon
#from classy_classification import ClassyClassifier
#import en_core_web_trf

data = {
    "furniture": ["This text is about chairs.",
               "Couches, benches and televisions.",
               "I really need to get a new sofa."],
    "kitchen": ["There also exist things like fridges.",
                "I hope to be getting a new stove today.",
                "Do you also have some ovens."]
}
nlp = en_core_web_trf.load()

nlp.add_pipe(
    "text_categorizer",
    config={
        "data": data,
        "model": "spacy"
    }
)

print(nlp("I am looking for kitchen appliances.")._.cats)

**Comment by davidberenstein1957** [comment]
This was fixed in release 0.6.3 @benhealthee . Thanks for bringing the issue up.
