### ISSUE TITLE
Error when using spacy _trf models

### ISSUE THREAD

**Issue by kbillesk** [davidberenstein1957/classy-classification#37]
Hi,
thanks for the updates on the classifier. I have been using your classifier based on en_core_web_lg and wanted to try out en_core_web_trf to see performance improvements. 

import spacy
import os
import classy_classification  # noqa: F401
from collections import OrderedDict
from operator import itemgetter
from data_en import training_data
nlp = spacy.load("en_core_web_trf")
print("english pretrained model has been loaded")
nlp.add_pipe("text_categorizer", config={"data": training_data,"model": "spacy"})

When I do this, I get the following console output:

english pretrained model has been loaded
Traceback (most recent call last):

  File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Documents/Python Scripts/doc genres/examples/classifiertest.py:22
    nlp.add_pipe("text_categorizer", config={"data": training_data,"model": "spacy"})

  File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/spacy/language.py:795 in add_pipe
    pipe_component = self.create_pipe(

  File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/spacy/language.py:674 in create_pipe
    resolved = registry.resolve(cfg, validate=validate)

  File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/thinc/config.py:746 in resolve
    resolved, _ = cls._make(

  File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/thinc/config.py:795 in _make
    filled, _, resolved = cls._fill(

  File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/thinc/config.py:867 in _fill
    getter_result = getter(*args, **kwargs)

  File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/classy_classification/__init__.py:53 in make_text_categorizer
    return ClassySpacyInternalFewShot(

  File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/classy_classification/classifiers/classy_spacy.py:110 in __init__
    ClassySkeletonFewShot.__init__(self, *args, **kwargs)

  File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/classy_classification/classifiers/classy_skeleton.py:65 in __init__
    self.set_training_data()

  File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/classy_classification/classifiers/classy_skeleton.py:236 in set_training_data
    self.X = self.get_embeddings(X)

  File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/classy_classification/classifiers/classy_spacy.py:101 in get_embeddings
    embeddings.append(doc._.trf_data.model_output.pooler_output[0])

AttributeError: 'ModelOutput' object has no attribute 'pooler_output'

Thanks in advance for your help

Kristian

**Comment by davidberenstein1957** [comment]
Hi @kbillesk, I cannot seem to reproduce this. What package versions are you using? Can you provide me with a `pip list`?

**Comment by kbillesk** [comment]
Hi @davidberenstein1957 thanks for looking into this. Here is my pip list (conda/pip)

[piplist.csv](https://github.com/davidberenstein1957/classy-classification/files/11784944/piplist.csv)

Thanks for investigating

**Comment by davidberenstein1957** [comment]
hi @kbillesk Could you try instaling the latest version of classy-classificaiton?

**Comment by kbillesk** [comment]
I just did, and the error is still there. I just tried running your basic example with furniture and kitchen and it works as it should. I may suspect it could be an issue related to the training data. I am showing you the training data that I am using, that is stored in a file called data_en.py

`training_data = {
    "EN_sicknotice": [
        "I have catched a cold and will be home today.",
        "Katja is sick and will be staying home for the rest of the week.",
        "1. day sick 11-09-2018",
        "So I will not come in the office tomorrow",
        "I am sick with a fever and I don't expect to be ready for tomorrow.",
        "Pia is sick with Corona and will come back friday at the earliest.",
        "I have a sick noy home today with smallpocks so I will not be very responsive on my e-mail.",
    ],
    "EN_resignation": [
        "I wish to resign by 11-09.",
        "I resign my job",
        "I quit.",
        "wish to hand in my notice of resignation",
        "I resign today and will stop workiing on 31. marts this year.",
        "In accordance with my employment contract, I am resgigning by 31/10",
        "I do not want to be part of this company anymore. I quit!",
    ],
    "EN_cv": [
        "CURRICULUM VITAE",
        "Native language : Afrikaans (Fluent) OTHER LANGUAGE : English (Fluent)",
        "EMPLOYMENT HISTORY",
        "Duties include:",
        "REFERENCES Available upon request ",
        "Enrolled in Master studies at ",
        "WORK EXPERIENCE 11/2016-current",
    ],
    "EN_employmentcontract": [
        "Place of work: ",
        "Normal working hours",
        "Remuneration ",
        "Compensation package ",
        "non-disclosure ",
        "Probationary period ",
        "Conditions of termination ",
           ],
    "EN_verdict": [
        "defendant is found guilty",
        "judgement given on",
        "Case No: ",
        "Approved Judgment",
        "the prosecution case",
        "The appellant’s case",
        "The judge’s sentencing remarks",
        "The critical findings of fact were that:",
        "Conclusion",
    ],
    "EN_certficate_of_residence": [
        "Certificate of Residency",
        "To whom it may concern",
        "Residence Documentation",
        "Date of Issue",
        "Certifying Permanent Residence",
        "Place and date of issue",
        "",
    ],
    "EN_HR_information": [
        "salary",
        "annual income",
        "annual bonus",
        "remuneration",
        "contract of employment",
        ],
}
`

**Comment by davidberenstein1957** [comment]
That is correct. You are passing an empty value (""), which does not have pooler output. I should skip the values in my code. I will leave this issue open or you can create a PR if you are up to it. Thanks for following up at least. Underneath is a working version.

```python
training_data = { "EN_sicknotice": [ "I have catched a cold and will be home today.", "Katja is sick and will be staying home for the rest of the week.", "1. day sick 11-09-2018", "So I will not come in the office tomorrow", "I am sick with a fever and I don't expect to be ready for tomorrow.", "Pia is sick with Corona and will come back friday at the earliest.", "I have a sick noy home today with smallpocks so I will not be very responsive on my e-mail.", ], "EN_resignation": [ "I wish to resign by 11-09.", "I resign my job", "I quit.", "wish to hand in my notice of resignation", "I resign today and will stop workiing on 31. marts this year.", "In accordance with my employment contract, I am resgigning by 31/10", "I do not want to be part of this company anymore. I quit!", ], "EN_cv": [ "CURRICULUM VITAE", "Native language : Afrikaans (Fluent) OTHER LANGUAGE : English (Fluent)", "EMPLOYMENT HISTORY", "Duties include:", "REFERENCES Available upon request ", "Enrolled in Master studies at ", "WORK EXPERIENCE 11/2016-current", ], "EN_employmentcontract": [ "Place of work: ", "Normal working hours", "Remuneration ", "Compensation package ", "non-disclosure ", "Probationary period ", "Conditions of termination ", ], "EN_verdict": [ "defendant is found guilty", "judgement given on", "Case No: ", "Approved Judgment", "the prosecution case", "The appellant’s case", "The judge’s sentencing remarks", "The critical findings of fact were that:", "Conclusion", ], "EN_certficate_of_residence": [ "Certificate of Residency", "To whom it may concern", "Residence Documentation", "Date of Issue", "Certifying Permanent Residence", "Place and date of issue"], "EN_HR_information": [ "salary", "annual income", "annual bonus", "remuneration", "contract of employment", ], }
```

**Comment by kbillesk** [comment]
Thanks for the support
