### ISSUE TITLE
Spacy embeddings vs sentence transformer embeddings

### ISSUE THREAD

**Issue by swageeth** [davidberenstein1957/classy-classification#42]
Hi there,

I have been using the classy-classification library for a few multi-label text classification tasks lately. I believed that the use of sentence transformer embeddings would always generate better results compared to the spacy embeddings. However, during my recent project, resulted in the opposite.

Below are the code snips I used:
Space embeddings (this generated better results) -
`nlp = spacy.load("en_core_web_lg")
nlp.add_pipe("classy_classification", 
    config={
        "data": data,
        "model": "spacy",
        "multi_label": True,
        "config": {"seed": 11},
        "device": "gpu"
    }
)`

Sentence transformer embeddings -
`# NLP model
nlp = spacy.load("en_core_web_lg")
nlp.add_pipe("classy_classification", 
    config={
        "data": data,
        "model": "sentence-transformers/all-mpnet-base-v2",
        "multi_label": True,
        "config": {"seed": 11},
        "device": "gpu"
    }
)`

Will you be able to provide some guidance on when to use sentence transformer embeddings and when to use Spacy embeddings please?

Thank you

**Comment by davidberenstein1957** [comment]
Spacy embedding are normally based on aggregated word embedding but sentence transformers on transformer embeddings which generally should be able to better  process the inter-dependencies of semantic meaning by using attention and positional encoding.
